"""Taiwan warrant terms, point in time.

Crawls TWSE MOPS into a raw layer, then builds a dimension table and an SCD2
history that can be looked up as of any date. See README.md.
"""
import glob
import os
from pathlib import Path

#: Built tables and the raw crawl live here, overridable with
#: ``DATA_SDK_WARRANT_CACHE_PATH``. They are built once and read from every
#: study, so they sit on NFS beside the other data_sdk caches rather than
#: inside whichever repo happened to build them.
DEFAULT_CACHE_PATH = '/mnt/nfs/backup/warrant_history'

#: One-time TEJ Pro exports, read-only. Kept out of the cache directory: they
#: are never regenerated by this package, and the cache is disposable.
DEFAULT_TEJ_SEED_PATH = '/mnt/nfs/backup/tej_warrants'

TEJ_BASIC_INFO_GLOB = 'tej_warrant_raw_*.parquet'
TEJ_ADJUSTMENT_GLOB = 'tej_warrant_adjustment_*.parquet'


def cache_directory(override: str | Path | None = None) -> Path:
    if override is not None:
        return Path(override)
    return Path(os.environ.get('DATA_SDK_WARRANT_CACHE_PATH', DEFAULT_CACHE_PATH))


def tej_seed_directory(override: str | Path | None = None) -> Path:
    if override is not None:
        return Path(override)
    return Path(os.environ.get('DATA_SDK_TEJ_WARRANTS_PATH', DEFAULT_TEJ_SEED_PATH))


def find_tej_seed(pattern: str, seed_directory: Path | None = None) -> Path | None:
    """Newest export matching ``pattern``, or None.

    The exports are named with the range they cover
    (``tej_warrant_raw_20191231-20260812.parquet``), so a fresh drop sorts last.
    """
    directory = tej_seed_directory(seed_directory)
    matches = sorted(glob.glob(str(directory / pattern)))
    return Path(matches[-1]) if matches else None
